#?? ?? ?? ?? 8081
server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    #    ?? db ??? ???? 3? ?? ??
    #   ?? db
    url: jdbc:mysql://localhost:3306/bank?allowPublicKeyRetrieval=true&useSSL=false
    username: ssafy
    password: ssafy
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
