const PATH = {
  ROOT: "/",
  SIGNUP: "/signup",
  PASSWORD_SETTING: "/password-setting",
  FIGNER_SETTING: "/finger-setting",
  SPLASH: "/splash",
  CARDUPLOAD: "/signup/card-upload",
  PRIORITY: "/priority",
  LOGIN_FINGER: "/login/finger-password",
  LOGIN_PASSWORD: "/login/password",
  HOME: "/mainpage/home",
  PAYOFFLINE: "/pay/offline",
  CARDLIST: "/mainpage/cardlist",
  SCAN: "/scan",
  SCAN_CARDINFO: "/mainpage/cardlist/scan/card-info",
  CARD_DETAIL: "/mainpage/cardlist/detail/${cardId}",
  CARD_DETAIL_PURCHASED: "/mainpage/cardlist/detail/${cardId}/purchased",
  STATISTICS: "/mainpage/statistics",
  MYPAGE: "/mainpage/mypage",
  MYPAGE_WITHDRAWAL: "/mypage/withdrawal",
  PAYONLINE: "/pay/online",
  PAYONLINECOMPLETE: "/pay/online/complete",
  MAIN: "/mainpage",
} as const;

export { PATH };
