#?? ?? ?? 8080
server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/cocopay?allowPublicKeyRetrieval=true&useSSL=false
    username: ssafy
    password: ssafy
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
